### PR TITLE
Add Toad's for Oracle "edit" keyword in replacement of select.

### PR DESCRIPTION
**Pull request by PierreTechoueyres**

### CODE REVIEW

**Comment by alex-hhh** [comment]
I was not aware that "edit" was an SQL keyword in Oracle, and I could not find any information about it.  Can you point me to some docs about it?

**Comment by PierreTechoueyres** [comment]
Sorry, I misremembered. It's a TOAD's keyword (see https://support.quest.com/technical-documents/toad-for-oracle/12.1/guide-to-using-toad-for-oracle/25#TOPIC-127876).
I use it often in some scripts.
So I think now you would'nt add it to the list, but could you think of a way of customizing this ?

**Comment by alex-hhh** [comment]
Looks like the edit keyword is specific to TOAD itself, so it is not useful in an SQL file that you can send to an Oracle database.  I'm hesitant to add this to `sql-indent.el`, but I'm not sure how to customize this, other than maintaining your own private branch.

Are you actually using this keyword in files outside TOAD?

**Comment by PierreTechoueyres** [comment]
Yes and no.
Yes as I used to edit some non trivial scripts with Emacs and using them with TOAD and no as this is the only way I use this keyword outside TOAD.
What about a defcustom for this var ?

**Comment by alex-hhh** [comment]
Closing this -- "EDIT" seems to be TOAD specific, not even Oracle specific...

**Pull request closed without merging**
