### PR TITLE
Add %type, %rowtype and table prefix in function's return type.

### PR DESCRIPTION
**Pull request by PierreTechoueyres**
Allow correct indenting after and function declaration like bellow:

```
declare
  function dummy return my_user.my_table%rowtype;
  function dummy2 return my_user.my_table.my_col%type;
  var dummy3 number;
begin
  null;
end;
```

### CODE REVIEW

**Comment by alex-hhh** [comment]
Could you please add an indentation check test for this case?  The example you provided in the pull request description should be sufficient, just add it to the test-data together with a corresponding "-syn.eld" file.  Thanks.

**Comment by alex-hhh** [comment]
It looks like you forgot to add "test-data/pr33.sql" "test-data/pr33-syn.eld" to GIT, so the tests won't run on my computers.  Can you please add those files as well?

**Comment by PierreTechoueyres** [comment]
Oops, I'm stupid me ! should be ok now.

**Comment by alex-hhh** [comment]
Thanks for writing the tests.  As the test suite grows, we can be more confident that we don't break things that we previously fixed, so it is helpful to add test cases when things are updated (especially since the test SQL is usually already there).

**Pull request merged**
