### PR TITLE
Various minor improvements on left align SQL statments.

### PR DESCRIPTION
**Pull request by PierreTechoueyres**

### CODE REVIEW

**Comment by alex-hhh** [comment]
This actually broke the `sqlind-ert-pr17-indentation-left`, since the indentation rule has changed.

Can you please update the test? You will need to update the indentation offsets in `test-data/pr17-io-left.eld` as described in the `sql-indent-test.el` file.  Let me know if you have problems.

**Comment by PierreTechoueyres** [comment]
Sorry, I will need help.
When I  type ```M-x ert RET "^sqlind-" RET``` in the master branch I get:

```ert-results
Selector: "^sqlind-"
Passed:  1
Failed:  9 (9 unexpected)
Skipped: 0
Total:   10/10

Started at:   2017-05-31 20:06:52+0200
Finished.
Finished at:  2017-05-31 20:06:53+0200

FFFFFFFFF.

F sqlind-ert-case-stmt
    (ert-test-failed
     ((should
       (equal
	(cons info actual)
	(cons info expected)))
      :form
      (equal
       ("/home/ptechoueyres/Travail/VCS/emacs-sql-indent/test-data/case-stmt.sql:4"
	(case-clause . 63)
	(select-column-continuation . 52)
	(statement-continuation . 52))
       ("/home/ptechoueyres/Travail/VCS/emacs-sql-indent/test-data/case-stmt.sql:4"
	(case-clause . 70)
	(select-column-continuation . 52)
	(statement-continuation . 52)))
      :value nil :explanation
      (list-elt 1
		(cdr
		 (different-atoms
		  (63 "#x3f" "??")
		  (70 "#x46" "?F"))))))

F sqlind-ert-m-io
    (ert-test-failed
     ((should
       (equal
	(cons info actual)
	(cons info expected)))
      :form
      (equal
       ("/home/ptechoueyres/Travail/VCS/emacs-sql-indent/test-data/m.sql:2" . 0)
       ("/home/ptechoueyres/Travail/VCS/emacs-sql-indent/test-data/m.sql:2" . 4))
      :value nil :explanation
      (cdr
       (different-atoms
	(0 "#x0" "?
```

**Comment by alex-hhh** [comment]
It looks like the unit tests were dependent on my Emacs user settings.  I updated them to be independent of user settings.  Can you please try running them on `alex-hhh/master` from the console using the command (you might need to put in the full path to Emacs):

```
emacs -batch -Q --no-site-file -L . -l sql-indent-test.el -f ert-run-tests-batch-and-exit
```

Sorry for the inconvenience, but I want to make sure that the tests can be run on other machines.

**Comment by PierreTechoueyres** [comment]
Don't worry, I happy to help.
It works !!!
```log
Running 10 tests (2017-06-01 21:15:31+0200)
Indenting region...
Indenting region...done
   passed   1/10  sqlind-ert-case-stmt
Indenting region...
Indenting region...done
   passed   2/10  sqlind-ert-m-io
Indenting region...
Indenting region...done
   passed   3/10  sqlind-ert-m-syn
Indenting region...
Indenting region...done
   passed   4/10  sqlind-ert-pr17
Indenting region...
Indenting region...done
   passed   5/10  sqlind-ert-pr17-indentation-default
Indenting region...
Indenting region...done
   passed   6/10  sqlind-ert-pr17-indentation-left
Indenting region...
Indenting region...done
   passed   7/10  sqlind-ert-pr17-indentation-right
Indenting region...
Indenting region...done
   passed   8/10  sqlind-ert-pr18
Indenting region...
Indenting region...done
   passed   9/10  sqlind-ert-pr19
Indenting region...
Indenting region...done
   passed  10/10  sqlind-ert-pr7

Ran 10 tests, 10 results as expected (2017-06-01 21:15:32+0200)
```

**Comment by PierreTechoueyres** [comment]
I'll try to submit another test case for an statement continuation that doesn't work well.

**Comment by PierreTechoueyres** [comment]
When I wrote "It's works !!!" I mean that's working both in batch and interactive.

**Comment by alex-hhh** [comment]
Now that you got the test running, can you please update the failing tests?  See https://github.com/alex-hhh/emacs-sql-indent/pull/22#issuecomment-305165752

**Comment by PierreTechoueyres** [comment]
Normally I've updated the branch and the test seem to work.

**Comment by alex-hhh** [comment]
Thanks for updating the test

**Pull request merged**
