### PR TITLE
Correct indentation of comments inside a block.

### PR DESCRIPTION
**Pull request by PierreTechoueyres**
ex:
begin
  first_instruction;

  -- a comment

  second_instruction; -- align with previous instruction.
end;
/

### CODE REVIEW

**Comment by alex-hhh** [comment]
The existing sql0indent.el already aligns the sample SQL as you indicated.  Can you provide an example of SQL that is not correctly indented in the current sql-indent.el?  Thanks, Alex.

**Comment by PierreTechoueyres** [comment]
I'll try to retrieve the problematic example.

**Comment by alex-hhh** [comment]
Did you find the problematic code for this case?

**Comment by PierreTechoueyres** [comment]
No, and as everything seems to indent correctly for the example I close this issue.
Sorry for the noise.

**Pull request closed without merging**
